export const projectslist = [
  {
    title: 'Todo list Angular Signals',
    description: 'Just the well know "to do list" but using new signals() for the Angular framework.',
    year: 2023,
    image: 'todoapp',
    techs: ['html', 'javascript', 'css'],
    frontend: true,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/todo-angular-signals',
    webOk: true,
    webUrl: 'https://todo-app-angular-17-signal.web.app/',
  },
  {
    title: 'Trello Family',
    description: 'A Trello Clon for use  with my family.',
    year: 2021,
    image: 'trello',
    techs: ['html', 'python', 'pandas', ],
    frontend: true,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/trello-family',
    webOk: false,
    webUrl: '',
  },
  {
    title: 'Angular 17 E-Commerce',
    description: 'A simple cart app using signals() in Angular.',
    year: 2024,
    image: 'store-17',
    techs: ['html', 'python', 'pandas', ],
    frontend: true,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/store-angular-17',
    webOk: true,
    webUrl: 'https://store-angular-17-six.vercel.app/'
  },
  {
    title: 'Money controller in VUE',
    description: 'An expense controller with a svg graph.',
    year: 2022,
    image: 'cashexpenses',
    techs: ['html', 'javascript', 'css'],
    frontend: true,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/store-angular-17',
    webOk: true,
    webUrl: 'https://cashexpenses.netlify.app/',
  },
  {
    title: 'Start using VUE',
    description: 'The simple introduction to vue framework.',
    year: 2022,
    image: '',
    techs: ['html', 'javascript', 'css'],
    frontend: false,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/vue-for-start',
    webOk: false,
    webUrl: '',
  },
  {
    title: 'E-commerce AngularAuth',
    description: 'An e-commerce with user creation and roles admin + client. Using Auth.',
    year: 2021,
    image: 'angular-store',
    techs: ['html', 'python', 'pandas', ],
    frontend: true,
    backend: false,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/an-angular-store',
    webOk: true,
    webUrl: 'https://an-angular-store.web.app/home',
  },
  {
    title: 'Node Store',
    description: 'The back-end for an ecommerce using NodeJs.',
    year: 2024,
    image: '/assets/img/projects/an-angular-store.jpg',
    techs: ['html', 'python', 'pandas', ],
    frontend: false,
    backend: true,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/a-node-store',
    webOk: false,
    webUrl: '',
  },
  {
    title: 'Node for start',
    description: 'A simple introduction to understand Node.',
    year: 2024,
    image: 'an-angular-store',
    techs: ['html', 'python', 'pandas', ],
    frontend: false,
    backend: true,
    githubOk: true,
    githubUrl: 'https://github.com/martinpercu/node-for-start',
    webOk: false,
    webUrl: '',
  },
]
